name: Python

on: workflow_dispatch

jobs:
  python38:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - uses: actions/upload-artifact@v3
        with:
          name: python3.8
          path: ./build/*
  python39:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./build
      strategy:
        matrix:
          python-version: ["3.9"]

      steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - uses: actions/upload-artifact@v3
          with:
            name: python3.9
            path: ./build/*
  python310:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - uses: actions/upload-artifact@v3
        with:
          name: python3.8
          path: ./build/*